# Generated by Django 4.1 on 2023-10-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_id',
            field=models.IntegerField(null=True),
        ),
    ]
