# Generated by Django 4.1 on 2023-12-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(help_text='Firebase user device token', max_length=250, null=True),
        ),
    ]
