# Generated by Django 4.1 on 2023-10-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_matchplayer_player_credits_matchplayer_player_points_and_more'),
        ('cricket', '0004_team_flag'),
    ]

    operations = [
    ]
