# Generated by Django 4.1 on 2023-10-20 11:53

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_merge_20231017_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='win_message',
            field=models.CharField(max_length=200, null=True),
        )
    ]
