# Generated by Django 4.1 on 2023-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_alter_match_win_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='prize_distribution',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userteamcontest',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('head_to_head', 'Head To Head'), ('medium', 'Medium Contest'), ('mega', 'Mega Contest'), ('takes_all', 'Winner takes all'), ('take_back', 'Take back')], max_length=15),
        ),
        migrations.AlterField(
            model_name='contest',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
