# Generated by Django 4.1 on 2023-10-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_contest_is_private_contest_prize_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
