# Generated by Django 4.1 on 2023-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0008_alter_team_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='association_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='uid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
