# Generated by Django 4.1 on 2023-11-15 13:48

import alltime11.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricket', '0009_alter_tournament_association_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('slider_path', models.CharField(max_length=200, null=True)),
                ('deep_link', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to=settings.AUTH_USER_MODEL, validators=[alltime11.validators.validate_slider_creator])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
