# Generated by Django 4.1 on 2023-11-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0010_slider'),
        ('cricket', '0011_userteam_name_alter_userteamcontest_contest_and_more'),
    ]

    operations = [
    ]
