# Generated by Django 4.1 on 2023-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0012_merge_20231128_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uid',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
