# Generated by Django 4.1 on 2023-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0014_slider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='deep_link',
            field=models.CharField(max_length=250),
        ),
    ]
