# Generated by Django 4.1 on 2024-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0015_alter_slider_deep_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='delayed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(max_length=200),
        ),
    ]
