# Generated by Django 4.1 on 2023-12-02 10:14

import alltime11.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import utils.shortuuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('reward_type', models.CharField(choices=[('wallet_balance', 'Add wallet balance bonus'), ('join_contest', 'Join contest bonus'), ('signup', 'Signup reward')], max_length=15)),
                ('is_active', models.BooleanField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_redeem_count', models.IntegerField(default=1)),
                ('redeem_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('code', models.CharField(db_index=True, default=functools.partial(utils.shortuuid.generate, *(), **{'max_length': 10, 'prefix': 'C'}), max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_rewards', to=settings.AUTH_USER_MODEL, validators=[alltime11.validators.validate_contest_creator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
